import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { errorMessage } from '../services/api';

export default function AuthPage({ mode }) {
  const isRegister = mode === 'register'; const { login, register: registerUser } = useAuth(); const navigate = useNavigate(); const [serverError, setServerError] = useState(''); const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm();
  const submit = async (values) => { setServerError(''); try { await (isRegister ? registerUser({ name: values.name, email: values.email, password: values.password }) : login(values)); navigate('/'); } catch (error) { setServerError(errorMessage(error)); } };
  return <main className="auth-shell"><section className="auth-copy"><p className="eyebrow">URL Bookmark Manager</p><h1>Keep the good links close.</h1><p>A private, simple home for the websites you use every day.</p></section><section className="auth-card"><h2>{isRegister ? 'Create your account' : 'Welcome back'}</h2><p>{isRegister ? 'Start organizing in a few seconds.' : 'Sign in to see your bookmarks.'}</p>{serverError && <div className="alert">{serverError}</div>}<form onSubmit={handleSubmit(submit)} noValidate>{isRegister && <label>Name<input {...register('name', { required: 'Your name is required.', minLength: { value: 2, message: 'Use at least 2 characters.' } })} />{errors.name && <small>{errors.name.message}</small>}</label>}<label>Email<input type="email" autoComplete="email" {...register('email', { required: 'Email is required.', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Enter a valid email.' } })} />{errors.email && <small>{errors.email.message}</small>}</label><label>Password<input type="password" autoComplete={isRegister ? 'new-password' : 'current-password'} {...register('password', { required: 'Password is required.', minLength: { value: 8, message: 'Use at least 8 characters.' } })} />{errors.password && <small>{errors.password.message}</small>}</label>{isRegister && <label>Confirm password<input type="password" {...register('confirmPassword', { required: 'Please confirm your password.', validate: (value) => value === watch('password') || 'Passwords do not match.' })} />{errors.confirmPassword && <small>{errors.confirmPassword.message}</small>}</label>}<button className="button auth-submit" disabled={isSubmitting}>{isSubmitting ? 'Please wait…' : isRegister ? 'Create account' : 'Log in'}</button></form><p className="switch-auth">{isRegister ? 'Already have an account?' : 'New here?'} <Link to={isRegister ? '/login' : '/register'}>{isRegister ? 'Log in' : 'Create an account'}</Link></p></section></main>;
}
