import { useCallback, useEffect, useMemo, useState } from 'react';
import BookmarkCard from '../components/BookmarkCard';
import BookmarkForm, { categories } from '../components/BookmarkForm';
import { useAuth } from '../context/AuthContext';
import * as bookmarkService from '../services/bookmarks';
import { errorMessage } from '../services/api';

export default function DashboardPage() {
  const { user, logout } = useAuth(); const [bookmarks, setBookmarks] = useState([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [category, setCategory] = useState(''); const [favorites, setFavorites] = useState(false); const [editor, setEditor] = useState(null); const [deleting, setDeleting] = useState(null); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setBookmarks(await bookmarkService.listBookmarks({ q: query || undefined, category: category || undefined, favorites: favorites || undefined })); } catch (cause) { setError(errorMessage(cause)); } finally { setLoading(false); } }, [query, category, favorites]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const stats = useMemo(() => ({ total: bookmarks.length, favorites: bookmarks.filter((item) => item.isFavorite).length }), [bookmarks]);
  const save = async (values) => { setSaving(true); try { await bookmarkService.saveBookmark(values, editor?.id); setEditor(null); setNotice('Bookmark saved.'); load(); } catch (cause) { setError(errorMessage(cause)); } finally { setSaving(false); } };
  const remove = async () => { try { await bookmarkService.deleteBookmark(deleting.id); setDeleting(null); setNotice('Bookmark deleted.'); load(); } catch (cause) { setError(errorMessage(cause)); } };
  const toggle = async (id) => { try { await bookmarkService.toggleFavorite(id); load(); } catch (cause) { setError(errorMessage(cause)); } };
  return <main className="dashboard"><header><div><p className="eyebrow">Your collection</p><h1>Welcome back, {user.name.split(' ')[0]}.</h1></div><div className="header-actions"><button className="button secondary" onClick={logout}>Log out</button><button className="button" onClick={() => setEditor({})}>+ Add bookmark</button></div></header>{(notice || error) && <div className={`alert ${error ? 'error' : 'success'}`}><span>{error || notice}</span><button onClick={() => { setError(''); setNotice(''); }} aria-label="Dismiss">×</button></div>}<section className="stats"><div><span>Total bookmarks</span><strong>{stats.total}</strong></div><div><span>Favorites</span><strong>{stats.favorites}</strong></div></section><section className="controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, URL, or category…" aria-label="Search bookmarks" /><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Filter category"><option value="">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><label className="favorite-check"><input type="checkbox" checked={favorites} onChange={(event) => setFavorites(event.target.checked)} /> Favorites only</label></section>{loading ? <p className="empty-state">Loading bookmarks…</p> : bookmarks.length ? <section className="bookmark-grid">{bookmarks.map((bookmark) => <BookmarkCard key={bookmark.id} bookmark={bookmark} onEdit={setEditor} onDelete={setDeleting} onFavorite={toggle} />)}</section> : <section className="empty-state"><h2>No bookmarks found</h2><p>{query || category || favorites ? 'Try changing your search or filters.' : 'Save your first useful link to get started.'}</p>{!query && !category && !favorites && <button className="button" onClick={() => setEditor({})}>Add your first bookmark</button>}</section>}{editor && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true"><h2>{editor.id ? 'Edit bookmark' : 'Add bookmark'}</h2><BookmarkForm bookmark={editor.id ? editor : undefined} onSave={save} onCancel={() => setEditor(null)} saving={saving} /></section></div>}{deleting && <div className="modal-backdrop" role="presentation"><section className="modal confirm" role="dialog" aria-modal="true"><h2>Delete bookmark?</h2><p>This will permanently remove “{deleting.title}”.</p><div className="form-actions"><button className="button secondary" onClick={() => setDeleting(null)}>Cancel</button><button className="button danger" onClick={remove}>Delete</button></div></section></div>}</main>;
}
